UIWeb/Controllers/PartidasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Entities;
using Services;

namespace UIWeb.Controllers
{
    public class PartidasController : Controller
    {
        private readonly Context _context;
        private PartidasServices _partidasServices;
        

        public PartidasController(Context context, PartidasServices partidasServices)
        {
            _context = context;
            _partidasServices = partidasServices;

        }

        // GET: Partidas
        public async Task<IActionResult> Index()
        {
            return View( _partidasServices.GetAllId());

            //return View(await _context.Partidas.ToListAsync());
        }

        // GET: Partidas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partida = await _context.Partidas
                .SingleOrDefaultAsync(m => m.ID == id);
            if (partida == null)
            {
                return NotFound();
            }

            return View(partida);
        }

        // GET: Partidas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Partidas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,PesoPromedio,Cantidad,Observaciones,Tipo,FechaIngreso")] Partida partida)
        {
            if (ModelState.IsValid)
            {
                partida.CantSinClasificar = partida.Cantidad;
                _context.Add(partida);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(partida);
        }

        // GET: Partidas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partida = await _context.Partidas.SingleOrDefaultAsync(m => m.ID == id);
            if (partida == null)
            {
                return NotFound();
            }
            return View(partida);
        }

        // POST: Partidas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,PesoPromedio,Cantidad,CantSinClasificar,Observaciones,Tipo,FechaIngreso")] Partida partida)
        {
            if (id != partida.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(partida);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PartidaExists(partida.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(partida);
        }

        // GET: Partidas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partida = await _context.Partidas
                .SingleOrDefaultAsync(m => m.ID == id);
            if (partida == null)
            {
                return NotFound();
            }

            return View(partida);
        }

        // POST: Partidas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var partida = await _context.Partidas.SingleOrDefaultAsync(m => m.ID == id);
            _context.Partidas.Remove(partida);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PartidaExists(int id)
        {
            return _context.Partidas.Any(e => e.ID == id);
        }
    }
}

UIWeb/Controllers/SubPartidasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Entities;
using Services;

namespace UIWeb.Controllers
{
    public class SubPartidasController : Controller
    {
        private readonly Context _context;
        private SubPartidasServices _subPartidaServices;
        private PartidasServices _partidasServices;

        public SubPartidasController(Context context, SubPartidasServices subPartidaServices, PartidasServices partidasServices)
        {
            _context = context;
            _subPartidaServices = subPartidaServices;
            _partidasServices = partidasServices;
        }

        // GET: SubPartidas
        public async Task<IActionResult> Index(int? id)
        {
            ViewData["PartidaID"] = id;
            var cantSinClasificar = _context.Partidas.Where(x => x.ID == id).Select(x=> x.CantSinClasificar).FirstOrDefault();
            ViewData["CantSinClasificar"] = cantSinClasificar;
            var context = _context.SubPartidas.Include(s => s.Partida).Where(s => s.PartidaID == id).Include(s => s.Pedido);
            return View(await context.ToListAsync());
        }

        // GET: SubPartidas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subPartida = await _context.SubPartidas
                .Include(s => s.Partida)
                .Include(s => s.Pedido)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (subPartida == null)
            {
                return NotFound();
            }

            return View(subPartida);
        }

        // GET: SubPartidas/Create
        public IActionResult Create(int? ID)
        {
            ViewData["PartidaID"] = ID;
            //ViewData["PartidaID"] = new SelectList(_context.Partidas, "ID", "ID");
            ViewData["PedidoID"] = new SelectList(_context.Pedidos, "ID", "ID");
            return View();
        }

        // POST: SubPartidas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PartidaID,PedidoID,CantCueros,Calidad,Estado,Eficiencia,Stock")] SubPartida subPartida)
        {
            if (ModelState.IsValid)
            {

                var partida = await _context.Partidas.FirstOrDefaultAsync(x => x.ID == subPartida.PartidaID);
                partida.CantSinClasificar = partida.CantSinClasificar - subPartida.CantCueros;
                _context.Add(subPartida);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = subPartida.PartidaID });
            }
            ViewData["PartidaID"] = new SelectList(_context.Partidas, "ID", "ID", subPartida.PartidaID);
            ViewData["PedidoID"] = new SelectList(_context.Pedidos, "ID", "ID", subPartida.PedidoID);
            return RedirectToAction("Index", new { id = subPartida.PartidaID });
        }

        // GET: SubPartidas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subPartida = await _context.SubPartidas.SingleOrDefaultAsync(m => m.ID == id);
            if (subPartida == null)
            {
                return NotFound();
            }
            ViewData["PartidaID"] = new SelectList(_context.Partidas, "ID", "ID", subPartida.PartidaID);
            ViewData["PedidoID"] = new SelectList(_context.Pedidos, "ID", "ID", subPartida.PedidoID);
            return View(subPartida);
        }

        // POST: SubPartidas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,PartidaID,PedidoID,CantCueros,Calidad,Estado,Eficiencia,Stock")] SubPartida subPartida)
        {
            if (id != subPartida.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subPartida);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubPartidaExists(subPartida.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PartidaID"] = new SelectList(_context.Partidas, "ID", "ID", subPartida.PartidaID);
            ViewData["PedidoID"] = new SelectList(_context.Pedidos, "ID", "ID", subPartida.PedidoID);
            return View(subPartida);
        }

        // GET: SubPartidas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subPartida = await _context.SubPartidas
                .Include(s => s.Partida)
                .Include(s => s.Pedido)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (subPartida == null)
            {
                return NotFound();
            }

            return View(subPartida);
        }

        // POST: SubPartidas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int PartidaID, int CantCueros)
        {
            var partida = _partidasServices.GetByID(PartidaID);
            partida.CantSinClasificar = partida.CantSinClasificar + CantCueros;
            _partidasServices.Update(partida);


            var subPartida = await _context.SubPartidas.SingleOrDefaultAsync(m => m.ID == id);
            _context.SubPartidas.Remove(subPartida);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { id = subPartida.PartidaID });
        }

        private bool SubPartidaExists(int id)
        {
            return _context.SubPartidas.Any(e => e.ID == id);
        }
    }
}

UIWeb/Views/Partidas/Create.cshtml
@model Entities.Partida

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Partida</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PesoPromedio" class="control-label"></label>
                <input asp-for="PesoPromedio" class="form-control" />
                <span asp-validation-for="PesoPromedio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Observaciones" class="control-label"></label>
                <input asp-for="Observaciones" class="form-control" />
                <span asp-validation-for="Observaciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" />
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

UIWeb/Views/Partidas/Delete.cshtml
@model Entities.Partida

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Partida</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PesoPromedio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PesoPromedio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CantSinClasificar)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CantSinClasificar)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Observaciones)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Observaciones)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

UIWeb/Views/Partidas/Details.cshtml
@model Entities.Partida

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Partida</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PesoPromedio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PesoPromedio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CantSinClasificar)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CantSinClasificar)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Observaciones)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Observaciones)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

UIWeb/Views/Partidas/Edit.cshtml
@model Entities.Partida

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Partida</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="PesoPromedio" class="control-label"></label>
                <input asp-for="PesoPromedio" class="form-control" />
                <span asp-validation-for="PesoPromedio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantSinClasificar" class="control-label"></label>
                <input asp-for="CantSinClasificar" class="form-control" />
                <span asp-validation-for="CantSinClasificar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Observaciones" class="control-label"></label>
                <input asp-for="Observaciones" class="form-control" />
                <span asp-validation-for="Observaciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" />
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

UIWeb/Views/Partidas/Index.cshtml
@using Entities;
@model IEnumerable<Entities.Partida>

@{
    ViewData["Title"] = "Index";
}

<h2>Lista de Partidas</h2>

<p>
    <a asp-action="Create">Agregar nueva </a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PesoPromedio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cantidad)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CantSinClasificar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Observaciones)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tipo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaIngreso)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SubPartidas)
                </th>
                <th>
                    Acciones
                </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PesoPromedio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantSinClasificar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Observaciones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaIngreso)
            </td>
            <td>
                @{if (item.SubPartidas == null)
                    {
                        <a asp-controller="SubPartidas" asp-route-id="@item.ID">Clasificar</a>
                    }
                    else
                    {
                        <script>
                            function myFunction() {
                                var x = $("#SelectedCountryId option:selected").val();

                                document.getElementById("demo").innerHTML = x;
                                }
                        </script>
                        <table>
                            <tr>
                                <td>
                                    <a asp-controller="SubPartidas" asp-action="Details" asp-route-id="26">Ver</a> &nbsp
                                </td>
                                <td>
                                    <select id="ddl1" asp-for="@item.ID" class="form-control"
                                            asp-items="@(new SelectList(
                                                            item.SubPartidas.Select(x=> new {
                                                                full = "ID: "+x.ID + " " +"Cant: "+ x.CantCueros,
                                                                ID = x.ID,
                                                                }),
                                                            "ID", "full"))">
                                        <option selected="selected" value="@item.ID">Please select</option>
                                    </select>
                                </td>
                            <tr />
                        </table>
                    }
                  }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                @if (item.CantSinClasificar != item.Cantidad)
                 {
                   <a asp-controller="SubPartidas" asp-route-id="@item.ID"> | Agregar Sub-Partida</a>
                 }
            </td>
        </tr>
}
    </tbody>
</table>

<button onclick="myFunction()">Try it</button>

<p id="demo"></p>